///////////////////////////////////////////////////////////
//  Packet.cs
//  Implementation of the Class Packet
//  Generated by Enterprise Architect
//  Created on:      05-May-2019 22:35:11
//  Original author: vule9
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Serialization;
using QueueApp.Model;

namespace QueueApp.Common
{
    [Serializable]
    public class Packet
    {
        #region Fields
        private String message;
        private RequestType typeOfRequest;
        private User user;
        #endregion

        #region Properties
       
        [XmlAttribute("message")]
        public String Message
        {
            get
            {
                return message;
            }
            set
            {
                message = value;
            }
        }

        [XmlAttribute("typeofrequest")]
        public RequestType TypeOfRequest
        {
            get
            {
                return typeOfRequest;
            }
            set
            {
                typeOfRequest = value;
            }
        }

        [XmlElement("user")]
        public User User
        {
            get
            {
                return user;
            }
            set
            {
                user = value;
            }
        }

        #endregion

        public Packet(String message, RequestType typeOfRequest, User user)
        {
            if(message == null || user == null)
            {
                throw new ArgumentNullException("Message or user can not be null.");
            }
            if(message == "")
            {
                throw new ArgumentException("Message can not be empty string");
            }
            this.message = message;
            this.typeOfRequest = typeOfRequest;
            this.user = user;
        }

        public Packet()
        {

        }

        ~Packet()
        {

        }


        #region Redefinitions

        public override string ToString()
        {

            return $@"From sever to {User}
Message: {Message}";

        }

        #endregion

    }//end Packet
}