///////////////////////////////////////////////////////////
//  RequestType.cs
//  Implementation of the Enumeration RequestType
//  Generated by Enterprise Architect
//  Created on:      05-May-2019 22:35:11
//  Original author: vule9
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace QueueApp.Common
{
    public enum RequestType : int
    {

        CREATE = 1,
        UPDATE,
        SUBSCRIBE

    }//end RequestType
}