///////////////////////////////////////////////////////////
//  ClientQueue.cs
//  Implementation of the Class ClientQueue
//  Generated by Enterprise Architect
//  Created on:      05-May-2019 22:35:11
//  Original author: vule9
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using QueueApp.Model;
using System.Collections.Concurrent;
using QueueApp.Common;

namespace QueueApp.Service
{
    public class ClientQueue : Queue
    {
        #region Fields
        private List<User> subscribedClients;
        #endregion

        #region Properties
        public List<User> SubscribedClients
        {
            get
            {
                return subscribedClients;
            }
            set
            {
                subscribedClients = value;
            }
        }
        #endregion

        public ClientQueue(String title) : base(title)
        {
            SubscribedClients = new List<User>();
        }

        ~ClientQueue()
        {

        }
    }//end ClientQueue
}