///////////////////////////////////////////////////////////
//  DbQueue.cs
//  Implementation of the Class DbQueue
//  Generated by Enterprise Architect
//  Created on:      05-May-2019 22:35:11
//  Original author: vule9
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Collections.Concurrent;
using QueueApp.Common;

namespace QueueApp.Service
{
    public class DbQueue : Queue
    {
        public DbQueue(String title) : base(title)
        {

        }

        ~DbQueue()
        {

        }
    }//end DbQueue
}