///////////////////////////////////////////////////////////
//  ServerQueue.cs
//  Implementation of the Class ServerQueue
//  Generated by Enterprise Architect
//  Created on:      05-May-2019 22:35:12
//  Original author: vule9
///////////////////////////////////////////////////////////

using System;
using QueueApp.Common;

namespace QueueApp.Service
{
    public class ServerQueue : Queue
    {
        public ServerQueue(String title) : base(title)
        {

        }

        ~ServerQueue()
        {

        }
    }//end ServerQueue
}